services:
  web:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend-app/.env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:strongpassword@mongodb:27017/employai?authSource=admin

    networks:
      - custom_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=strongpassword
      - MONGO_INITDB_DATABASE=employai
    volumes:
      - mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "27017:27017"
    networks:
      - custom_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mongodb:

networks:
  custom_network:
    driver: bridge